### ISSUE TITLE
Asyncio support?

### ISSUE THREAD

**Issue by sanderland** [cohere-ai/cohere-python#117]
Is there any interest for an async/aiohttp based client?

Advantages:

* Much lower overhead than threadpools
* Users who use the api as a step in their async codebase (e.g. fastapi) are not forced to block

Disadvantages:

* Needs significant refactoring to not end up with code duplication
* Extra (optional?) dependency

**Comment by argoopjmc** [comment]
I'm planning to make a rust crate for the Cohere API (with a tokio runtime), and will probably add bindings to call it from Python!

**Comment by sanderland** [comment]
Experimenting with this @ https://github.com/cohere-ai/cohere-python-aio

**Comment by argoopjmc** [comment]
Is this public yet?

**Comment by sanderland** [comment]
@argoopjmc No, and its future is rather uncertain. Feel free to add your use cases for something like this, which could help inform if/when it will be.
