### ISSUE TITLE
Expose response id in the sdk

### ISSUE THREAD

**Issue by CoderHam** [cohere-ai/cohere-python#135]
Expose the id for the response in addition to the id for each generation.

A sample json response is shared below. As we can see these ids are already present in the response json. This would be more useful now that we have a co.feedback endpoint that takes in the id as an input. 

```
{"id":"49d08f39-dcfc-4762-a519-71eaabc46edb","generations":[{"id":"fd401066-6798-432a-b591-1a0e5893f9b2","text":" This is dummy text"}], "prompt":"Some text"}
```

But when we print(generationResponse) we get the following. As we can see, no Id fields.
```
cohere.Generations {
        generations: [cohere.Generation {
        text:  Some text
        likelihood: None
        token_likelihoods: None
}]
        return_likelihoods: NONE
}
prediction: [cohere.Generation {
        text:  This is dummy text
        likelihood: None
        token_likelihoods: None
}]
```

Additionally it might serve us well to distinguish the two ids if co.feedback cannot consume both

**Comment by mkozakov** [comment]
This is tracked internally, so closing this as a duplicate
