### ISSUE TITLE
Feature request: batch request

### ISSUE THREAD

**Issue by perone** [cohere-ai/cohere-python#174]
It would be nice if the API could provide an endpoint where it could accept a batch request, like for example the `Co.Generate` could accept a list of prompts. It is not very efficient both from the inference perspective at the backend and for the client, having to execute multiple calls with all the overhead of each call instead of just batching it and doing a single call with all prompts.

**Comment by amorisot** [comment]
There's an undocumented feature to do this, [here](https://github.com/cohere-ai/cohere-python/blob/main/cohere/client.py#L88)!
