### ISSUE TITLE
cohere function to detect language is not working 

### ISSUE THREAD

**Issue by greedyboyy** [cohere-ai/cohere-python#227]
Hello, i'm trying to use the API to detect a language, and including if i am doing the base code that the documentation provides, this still not working.

```
import cohere
co = cohere.Client('myapi')

response = co.detect_language(
  texts=['Hello world', "'Здравствуй, Мир'"]
)
print(response)
```

I don't know why this is not working, the 'error' i am getting is:
<cohere.responses.detectlang.DetectLanguageResponse object at 0x02307F50>

**Comment by mkozakov** [comment]
This technically works, however the String representation of the DetectLanguageResponse object is not great :P

1. what you want is response.results
2. I put up a PR to improve the string representation of the object: https://github.com/cohere-ai/cohere-python/pull/228
