### ISSUE TITLE
Co.Classify now (incorrectly?) insists upon examples on custom models

### ISSUE THREAD

**Issue by peterc** [cohere-ai/cohere-python#239]
In [the docs for Co.Classify](https://docs.cohere.com/reference/classify) it says:

> Note: [Custom Models](https://docs.cohere.com/training-representation-models) trained on classification examples don't require the examples parameter to be passed in explicitly.

However, as of commit https://github.com/cohere-ai/cohere-python/commit/7daa907d92f5016b0aed83456f63802f500f1249 this is no longer true, and not passing in examples results in an error `cohere.error.CohereError: examples must be a non-empty list of ClassifyExample objects.`

This is because the code in the commit added a condition where examples are only skipped if `preset` is also being used, but I don't believe a preset is necessary in order to use a custom model in this way (or is it?)

**Comment by mayoor** [comment]
+1 on the above issue.

**Comment by abdullahkady** [comment]
Thank you for reporting! This should be fixed in 4.6.1 (#240) now.
