### ISSUE TITLE
API Documentation Broken

### ISSUE THREAD

**Issue by maxTarlov** [cohere-ai/cohere-python#304]
The Python SDK API reference is not building correctly on Read the Docs. Only headers load, all body text is absent. 

https://cohere-sdk.readthedocs.io/en/latest/cohere.html#api

**Comment by maxTarlov** [comment]
![image](https://github.com/cohere-ai/cohere-python/assets/51882792/05d8600c-52a3-450e-bcc0-2349cde2e52b)

**Comment by akshatpoddar** [comment]
This issue does not occur while making the html locally. Might be an issue with the hosting environment.
