### ISSUE TITLE
rerank (async client) does not have parameter return_documents 

### ISSUE THREAD

**Issue by cirezd** [cohere-ai/cohere-python#339]
https://github.com/cohere-ai/cohere-python/blob/5e9e872cd75ebea3c2091dd043b875b494f21535/cohere/client_async.py#L495C33-L495C38

Hello, the reranker (async client) does not have parameter return_documents. It is hard-coded to `False` in the code above.

**Comment by mehrdad-es** [comment]
Hi @cirezd, you might be right in that there might not be a specific reason for this hard coding. @mkozakov , @lfayoux can you confirm? 

If there is no specific reason then this could be fixed with a simple PR.
