### ISSUE TITLE
some clarity on System message for ChatCohere ( command)

### ISSUE THREAD

**Issue by gowtham07** [cohere-ai/cohere-python#393]
Hello,

Amazing work by COHERE to provide a lot of resources online for people to try and implement stuff. Recently I was using semantic routers with cohere models. I want my agent to work as a assistant bot for a 'imaginary company', I send the info in the system prompt. When I ask a question like " what is your company's name and product do you offer", it says cohere. So is there anyway that I can make the model to behave as travel assistant bot? How do I have to make use of the system prompts?

Thanks!

**Comment by elaineg** [comment]
Hi, our equivalent of writing a system message is done through the `preamble` parameter
