### ISSUE TITLE
Force Cohere LLM to generate only Json format as expected without any other unnecessary text

### ISSUE THREAD

**Issue by thnguyendn** [cohere-ai/cohere-python#394]
Hello,

I do not really know if it is a right place to ask my question, but did not find any appropriate ones.

I would like to know if when we ask Cohere to generate text completion (or chat) through API, do we have a solution to **force Cohere to generate only Json validated format without any introduction text at the beginning** ?

I have used a **prompt-engineering approach** to require a Json validated-format in my prompt by adding either : 
"your output is only of json valid structure [{{'key1': value1, 'keys2': [values], 'key3': value3}}]"
Or 
"your output is only of json valid structure [{{'key1': value1, 'keys2': [values], 'key3': value3}}], without any introduction text ..."

As result, Cohere always add an introduction text at the beginning as follows : 
"Here is the JSON format generated from the information provided:
'''json
[useful_information_situated_here]
'''
"

What I really want to receive as output is only the Json valid format inside of parenthesis (i.e. useful_information_situated_here)

**Comment by aanaseer** [comment]
I think [this article](https://txt.cohere.com/validating-llm-outputs/) on validating LLM outputs using [Guardrails AI](https://github.com/guardrails-ai/guardrails) might be helpful.

**Comment by elaineg** [comment]
Hi, thanks for filing this ticket, it's on our roadmap to add forced json outputs.

**Comment by thnguyendn** [comment]
thank you for all of your replies @aanaseer @elaineg. Looking forward to test it later...
