### ISSUE TITLE
Different message validation for Stream=True and Stream=False

### ISSUE THREAD

**Issue by ysolanky** [cohere-ai/cohere-python#423]
When using the `Stream = True` parameter in cohere.chat and passing an empty message `" "` with a tool call result, I get no errors rather just a response 400 from the API. With `Stream = False`, I get a perfectly good response. 

Wondering if there is different validation for Stream? The parameters being sent to cohere.chat are identical in both cases. Parameters that I am sending are: `preamble, chat_history, tools, tool_results, messages, model`

**Comment by billytrend-cohere** [comment]
@ysolanky sorry for the delay. I can't repro this now in the latest sdk, please reopen if this is an ongoing issue!
