### ISSUE TITLE
Deprecated co.create_custom_model without new alternative for Python SDK

### ISSUE THREAD

**Issue by kenza-ily** [cohere-ai/cohere-python#448]
Hi,

I'm trying to fine-tune a model with `co.create_custom_model`, following the API documentation (last updated 17 days ago).

```python
# start the fine-tune job using this dataset
finetune = co.create_custom_model(
  name="single-label-ft", 
  dataset=single_label_dataset,
  model_type="CLASSIFY"
)

finetune.wait() # this will poll the server for status updates
print(f"fine-tune ID: {finetune.id}, fine-tune status: {finetune.status}")
``` 

I get the following error:
     58     def fn(*args, **kwargs):
---> 59         raise ValueError(
     60             f"Since python sdk cohere==5.0.0, the function {fn_name}(...) has been deprecated. "
     61             f"Please update your code. Issues may be filed in https://github.com/cohere-ai/cohere-python/issues."

ValueError: Since python sdk cohere==5.0.0, the function create_custom_model(...) has been deprecated. Please update your code. Issues may be filed in https://github.com/cohere-ai/cohere-python/issues.
_____

I've looked through the API documentation, the [migration guide](https://pypi.org/project/cohere/), etc. but no alternative is proposed: will it still be possible to fine-tune from the Python SDK with Cohere 5?

Thank you for your help

**Comment by elaineg** [comment]
Hi there, thanks for comment. I've just realized that the finetuning API reference on our documentation has not been updated to include the Python SDK. With v5, custom_models has been updated to fine-tuning. You can see all the supported methods here: [https://github.com/cohere-ai/cohere-python/tree/main/src/cohere/finetuning/finetuning/types](https://github.com/cohere-ai/cohere-python/tree/main/src/cohere/finetuning/finetuning/types)
