### ISSUE TITLE
Update tokenizers version 

### ISSUE THREAD

**Issue by kilimchoi** [cohere-ai/cohere-python#483]
Is it possible to update the tokenizers' version? We're using the latest transformers python package and it requires tokenizers' version to be >=0.19,<0.20

**Comment by billytrend-cohere** [comment]
Hey, bumped it to ^0.19 in 5.3.3, thanks for reporting!

**Comment by ShreyPandit** [comment]
Hi, This issue got resolved with 5.3.3 but again pops up with the latest 5.5.6
