### ISSUE TITLE
help with cohere in codegpt

### ISSUE THREAD

**Issue by isefol** [cohere-ai/cohere-python#486]
I'm a total noob in programming right away. I have specified my api key from cohere in codegpt, but I keep getting this error. what is it? What do I need to do?

![0427002420](https://uploads.linear.app/55d565ca-7e02-4768-ae1c-67c88e5e1d7c/41134ec2-7f65-4afb-81dd-cd29f5d02552/2e168fdc-6a20-4c62-9a37-4e954ca1df0b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzU1ZDU2NWNhLTdlMDItNDc2OC1hZTFjLTY3Yzg4ZTVlMWQ3Yy80MTEzNGVjMi03ZjY1LTRhZmItODFkZC1jZDI5ZjVkMDI1NTIvMmUxNjhmZGMtNmEyMC00YzYyLTlhMzctNGU5NTRjYTFkZjBiIiwiaWF0IjoxNzE0Mzg2OTU0LCJleHAiOjMzMjg0OTQ2OTU0fQ.b_9EEeEtuwyqCR16qRA-NQwPQixyAwORkD_Jj_IE-hA)

**Comment by elaineg** [comment]
Hi there, sorry to see this error. A 403 error isn't coming from our model. Did you set an API key anywhere?

**Comment by isefol** [comment]
> Hi there, sorry to see this error. A 403 error isn't coming from our model. Did you set an API key anywhere?

Yeah, I've tried it several times, I reinstalled the codegpt extension several times too, but it didn't work out.

**Comment by elaineg** [comment]
Hi- Would you be able to email support@cohere.com with your user IP and account email address? It may have something to do with IP blocking. Thank you and sorry for the inconvenience

**Comment by elaineg** [comment]
Closing because this has been open without response for 2 weeks.
