### ISSUE TITLE
Can't fine tune latest reranker

### ISSUE THREAD

**Issue by SardarArslan** [cohere-ai/cohere-python#492]
I am trying to fine tune the multilingual_v3.0 reranker with python sdk, but when I write version =v_3.0 or 3.0.0, it shows 2.0.0 in the fine-tuning response. 
My code: 
```
ft=co.finetuning.create_finetuned_model(
    request=FinetunedModel(
        name="reranker",
        settings=Settings(
            base_model=BaseModel(
                base_type="BASE_TYPE_RERANK",
                name="multilingual",
                version='v_3.0'
               
            ),
            dataset_id="reranking-dataset-bb0747",
        ),
    ),
)
```
ft response:

`CreateFinetunedModelResponse(finetuned_model=FinetunedModel(id='87db8998-fe68-4141-b555-f99359f97199', name='reranker', creator_id='22c4a2bb-f291-457b-925a-2c86440328e4', organization_id='42051e19-e7b7-4f22-b3e8-6273ed1c8aad', settings=Settings(base_model=BaseModel(**name='multilingual', version='2.0.0',** base_type='BASE_TYPE_RERANK', strategy='STRATEGY_TFEW'), dataset_id='reranking-dataset-bb0747', hyperparameters=None, multi_label=None), status='STATUS_QUEUED', created_at=datetime.datetime(2024, 5, 7, 9, 24, 19, 147257, tzinfo=datetime.timezone.utc), updated_at=datetime.datetime(2024, 5, 7, 9, 24, 19, 147257, tzinfo=datetime.timezone.utc), completed_at=None, last_used=None))`

**Comment by elaineg** [comment]
We didn't add fine-tuning to v3 - We'll audit documentation for any mentions of it.

**Comment by SardarArslan** [comment]
Thanks. Do you guys plan on adding fine tuning for v3 in the near future?

**Comment by elaineg** [comment]
Yes, though we don't have an ETA yet. Closing for now but I'll keep you posted if we land on a date.
