### ISSUE TITLE
Web Connector not Applied using Python Library

### ISSUE THREAD

**Issue by AbdullahADhaim** [cohere-ai/cohere-python#504]
This code works fine and doesn't give any error, but the web connector isn't properly working and the result has ZERO documents unless I use a normal HTTP POST Request to `https://production.api.cohere.ai/v1/chat` it will work 

`co.chat(model="command-r-plus", message=PROMPT, preamble=PREAMBLE, connectors=[{"id": "web-search"}])`

**Comment by billytrend-cohere** [comment]
Discussed over discord. Requires prompt engineering/guided generation
