### ISSUE TITLE
When using BedrockClient, the response does not contain meta fields for billed tokens

### ISSUE THREAD

**Issue by c64er4ever** [cohere-ai/cohere-python#531]
Hi,
I am using both Client and BedrockClient.
When using Client, I can access fields:
response.meta.billed_units.input_tokens
response.meta.billed_units.output_tokens
However, when using BedrockClient, the response does not seem to contain any meta fields, so I cannot check the number of billed input and output tokens.
I tested direct calls to Bedrock via boto3 invoke, and in this case I saw that I am getting the billed tokens using special x-amzn-bedrock header fields. It seems that currently the client does not handle these fields.
Thanks
Guy

**Comment by billytrend-cohere** [comment]
Hey @c64er4ever ! Thanks for letting us know about this. I will have a fix for you this week or next. Best, Billy

**Comment by c64er4ever** [comment]
That's great, thanks Billy!

**Comment by billytrend-cohere** [comment]
I have a PR here @c64er4ever, will ping when it's released https://github.com/cohere-ai/cohere-python/pull/537

**Comment by billytrend-cohere** [comment]
This is released in the latest python version 5.6.2
