### ISSUE TITLE
CI to Publish Our PyPi Server

### ISSUE THREAD

**Issue by OrenLeung** [cohere-ai/cohere-python#55]
CI to Publish Our PyPi Server on all merges/pushes to `main` so that we dont need to manually build and upload every time.
- Github Action
- https://pythonprogramming.org/automatically-building-python-package-using-github-actions/

cc: @jimwu6 @choicallum

**Comment by alexguo247** [comment]
This is addressed in https://github.com/cohere-ai/cohere-python/pull/49
