### ISSUE TITLE
About making botocore an optional dependency

### ISSUE THREAD

**Issue by pushkarnimkar** [cohere-ai/cohere-python#556]
**Describe the improvement**

I am installing `cohere-python` in a docker image. I don't use any AWS service, nevertheless the library still installs the `boto3` dependency that takes around 25 MB of space. Removing the dependency or making it optional can reduce size of the image. 

[Example](https://python-poetry.org/docs/pyproject/#extras) of optional dependencies when using poetry. 

Thank you!

**Comment by pushkarnimkar** [comment]
Hello! Just checking again to see if there's any interest :)

**Comment by jjfeore** [comment]
This would be a nice change, and it also seems like this is actually intended.

If you look at their poetry.toml, it's clear that boto3 and sagemaker are both listed as part of the "aws" extra that should only be installed with that flag. Looking in the actually METADATA of the package though, I see that it lists:

`
Requires-Dist: boto3 (>=1.34.0,<2.0.0)
Requires-Dist: sagemaker (>=2.232.1,<3.0.0)
`

It is a bit obnoxious that these two optional dependencies are sneaking in and bloating the build right now. I'm resolving this by manually excluding them when I pip-compile, but it'd be nice to have a less hacky fix.
