### ISSUE TITLE
Unable to add the documents to the vector store as I am getting Internal server error

### ISSUE THREAD

**Issue by crtejavardhanreddy** [cohere-ai/cohere-python#563]
**SDK Version (required)**
Provide the version you are using. To get the version, run the following python snippet
```python
import cohere

print(cohere.__version__) # 5.6.1
```

**Describe the bug**
1. Getting Internal server Error
` Retrying langchain_cohere.embeddings.CohereEmbeddings.embed_with_retry.<locals>._embed_with_retry in 4.0 seconds as it raised InternalServerError: status_code: 500, body: {'message': 'internal server error, this has been reported to our developers. id b8361921-90ee-4ce3-aa18-f2bdda5a6a8b'}.`
2. This is my code that I am using for the adding data and I am using embed-english-v2.0 as 4096 dimensions

**Screenshots**
1. Code : 
![image](https://github.com/user-attachments/assets/2b342cc2-24cc-452c-9344-758736407be7)
2. Error :
![image](https://github.com/user-attachments/assets/79ed1f90-43c3-4389-b711-a837e769b175)

**Comment by mkozakov** [comment]
This should have been addressed, can you please confirm that you're able to run this?

**Comment by mkozakov** [comment]
Closing as stale
