### ISSUE TITLE
Old Document Issues

### ISSUE THREAD

**Issue by minomizuha** [cohere-ai/cohere-python#567]
```py
for event in stream:
    if event.event_type == "text-generation":
        print(event.text, end='')
```

Then, apparently, I will throw up an error.
It worked when I made it look like the following, but is the document still old...?
You don't have to reply, but please confirm when you have time.

```py
if stream and hasattr(response, 'text'):
     generated_text = response.text
else:
     generated_text = "Error: The expected response was not returned. "
```

By any chance, if was the problem...?
Is it probably like this?

```py
if stream and hasattr(response, 'text'):
     generated_text = response.text
else:
     generated_text = "Error: The expected response was not returned. "
print(generated_text)
```

**Comment by mkozakov** [comment]
hey @minomizuha sorry for the delay. i'm having trouble understanding your question, can you please share a complete code snippet and the error message that you're seeing? events of type text-generation will always have `text` in them, i'm not sure why you were seeing an error

**Comment by mkozakov** [comment]
Closing due to staleness. Please re-open if you continue to experience this issue
