### ISSUE TITLE
sagemaker increases import time from ~1 sec to ~10 seconds

### ISSUE THREAD

**Issue by ben-albrecht** [cohere-ai/cohere-python#593]
**SDK Version(s) & bug reproducer**

```python
import time
t = time.time()
import cohere
print(time.time() - t)

print(cohere.__version__)
```

```
10.188275575637817
5.11.0
```

```
0.7559852600097656
5.10.0
```

This also significantly impacts import time of packages that depend on cohere, such as [instructor-ai/instructor](https://github.com/instructor-ai/instructor).

**Comment by neilkumar** [comment]
It's also adding a lot of noise to the logs 

```
[10/16/24 02:15:29] INFO     INFO  Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml                                                                                                                                                                            config_utils.py:243
                    INFO     INFO  Not applying SDK defaults from location: /home/app/.config/sagemaker/config.yaml       
```

**Comment by andaldanar** [comment]
Facing the same issue. Just want to use the Rerank models directly from the Cohere API, but the `sagemaker` import (and others like `mlflow`, `docker`, etc.) are dealbreakers for our use case.

It'd be great if we could install only the core Cohere platform stuff by default, with optional installs for specific platforms (Bedrock, SageMaker, Azure, GCP, Oracle OCI)

This way, we can avoid the slow imports and unnecessary dependencies when we're just using the basic Cohere API. Could we have a 'lite'/`core` version that doesn't pull in all these extra packages?

Thank you!

**Comment by ben-albrecht** [comment]
To speed up imports until this is fixed on the next release, you can switch to previous release:

```
uv pip install cohere==5.10.0
```

**Comment by ben-albrecht** [comment]
@billytrend-cohere @1vn - I believe the issue began with #588, with the introduction of [
](https://github.com/aws/sagemaker-python-sdk) as a dependency.

Perhaps you could make this an optional dependency, such that the default install does not increase import time by ~10 seconds?

e.g.

```
uv pip install cohere[sagemaker]
```

**Comment by billytrend-cohere** [comment]
Ok I think we're good but please re-open if you have related issues!

I see:

```
1.8758995532989502
5.11.1
```

```
sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /home/codespace/.config/sagemaker/config.yaml
2.3514339923858643
5.11.0
```
