### ISSUE TITLE
Numpy versioning

### ISSUE THREAD

**Issue by mgorinova** [cohere-ai/cohere-python#622]
Hello cohere! 

This dependency requirement for numpy is preventing my company from updating to the latest version of the cohere api: https://github.com/cohere-ai/cohere-python/blob/05fe9e7ffc962295f2fc6a24d114ca1eaa365cb6/poetry.lock#L1606

Is there are reason to restrict the numpy version to `<2.0`? Is there no support for the latest numpy (2.2.0)?

Thanks!

**Comment by billytrend-cohere** [comment]
hey thanks for reporting, this is because of our sagemaker dependency. Looking into how to resolve this 🙏  https://github.com/aws/sagemaker-python-sdk/issues/4882

**Comment by billytrend-cohere** [comment]
hey @mgorinova, we have now dropped all the aws deps from the sdk. Users will have to install them manually but I think this is a net positive for most developers! please try 5.13.4

**Comment by mgorinova** [comment]
Fantastic, thank you @billytrend-cohere!
